### ISSUE TITLE
Faikin automatic mode

### ISSUE THREAD

**Issue by ckvsoft** [revk/ESP32-Faikin#148]
**Faikin hardware**
AMAZON

**Daikin hardware**
FTXM35R

**Describe the bug**
I'm not sure if it's a bug or intentional.

If I change the temperature e.g. Set it to 25 degrees and set the settings to +-1/2 degrees, I noticed that the air conditioning only heats up to 24.5 degrees and then turns the fan down.

If the temperature is not up to 25.5 degrees, the fan should be turned down and heated up again at 24.5 degrees. Am I misunderstanding the +-1/2?

**Additional context**

**Comment by revk** [comment]
Now sure I entirely follow what you are saying.

Yes, 25℃ setting with ±½℃ would aim for somewhere within 24½℃ and 25½℃, so heating stopping around 24½℃ makes sense, as would cooling stopping around 25½℃. Within the range 24½℃ to 25½℃ no heating or cooling is needed.

When you start the fan is normally set high and goes back low once in the band you have selected, so that also makes sense. The fan then adjusts to increase if it find that heating (or cooling) is not working, i.e. not reaching the target band, and reduce if staying in the band.

If you set 25½℃ and ±½℃ then it should heat to 25℃ or cool to 26℃ and stop to keep in range 25℃ to 26℃, yes?

That said, it is aiming to predict the temperature a few minutes ahead, and external factors can change things (temperature, and necessary fan speed, and so on). The prediction can mean it stops heating before reaching the temperature, but it should start again if it does not continue on to the temperature. In general I find this works quite well.

**Comment by ckvsoft** [comment]
The way you describe it makes perfect sense.

thanks for the explanation. What then happens with the +- turned off? Do you then try to maintain exactly this temperature?

I was just used to it differently from my old heating system. Thanks

**Comment by revk** [comment]
Turn off means the "faking automatic" mode is off, and it does not try and take over.

I hope that makes sense.

**Comment by ckvsoft** [comment]
> Turn off means the "faking automatic" mode is off, and it does not try and take over.
> 
> I hope that makes sense.

Yes, not quite.
If +- is off and auto is on, is the automatic still switched off?

**Comment by revk** [comment]
Ah, I probably need to add more to the manual.

There is also an "auto" to automatically turn the aircon on when way outside temperature range, and turn off if within range a long time. I think that only applies if the ± is set.

**Comment by ckvsoft** [comment]
OK. And then what does it do?
target [24.5,25.5] if I use an external thermometer?
control = {
  "env": 24.1,
  "target": [
    25.5,
    26.5
  ]
}

**Comment by ckvsoft** [comment]
Understood. I use an external Raspberry thermostat with LCD touch and am currently in the process of adapting it so that I can control Faikin with it. Thanks for the clarification

**Comment by revk** [comment]
That sounds cool.

**Comment by ckvsoft** [comment]
> That sounds cool.

![grafik](https://github.com/revk/ESP32-Faikin/assets/16374447/1e01a6ac-441b-4443-b897-45226ecbff25)
