### ISSUE TITLE
[BUG] Can no longer control FTX15NMVJU

### ISSUE THREAD

**Issue by dodgeboy** [revk/ESP32-Faikin#473]
I am using a Faikin S3-MINI-N4-R2, purchased from Amazon UK a few months back.  It is connected to a Daikin FTX15NMVJU.  I used to be able to use the Faikin to control the unit (on, off, cool, fan, etc.) but I noticed today that while it is still receiving status updates (mode, fan rpm, cooling status, etc.), if I try to control it nothing happens.  For example, if I try to turn the unit off from the Faikin web interface, the switch turns off but nothing happens.  Then about 10 seconds later the switch turns back on.  

I have auto update enabled, so I'm assuming a Faikin update in the last month or two caused this issue (I don't use it to control the unit often, so I'm not sure when it started failing).  

If I look at MQTT, I see a ton of messages in the "cannot-tx" category.  Here are a couple examples:

{"protocol":"S21","cmd":"D1","payload":"30364041","text":"06@A"}
{"protocol":"S21","cmd":"D1","payload":"30334A41","text":"03JA"}

I also see this in the "failed-set" category:
{"power":false,"mode":"F"}

And a ton of these in the "comms" category:
{"protocol":"S21","timeout":true,"data":"0247493546"}
{"protocol":"S21","badsum":"E8","data":"02473131B34B416703"}

{"G1":"13JA","G2":"4:\u0000\u0080","G3":"000\u0000"}

However it still appears to be able to read status from the unit just fine.  What could be causing this?

**Comment by revk** [comment]
That usually means it is not getting replies. The time-out and badsum suggest a communications issue of some sort. If that is bad enough you may see some status and not a lot more. Worth selecting beta on s/w updates as well anyway, but doubt that will help.

I'd double check wiring, no lose wires, etc.

Otherwise it could be simply a hardware issue of some sort and need replacing. Obviously if only a few months old, you can do a refund request to Amazon.
