### ISSUE TITLE
Compatibility list

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/ESP32-Faikin#51]
This information is missing from docs, would be useful to add. What AC models is this tested with? What models use S21 and what models use "new" ?

**Comment by revk** [comment]
That's what the wiki is for, which lists a number of models, and is linked from the readme. So what am I missing?

**Comment by revk** [comment]
![image](https://github.com/revk/ESP32-Faikin/assets/996983/52aa3d3a-7123-461b-8d72-700374b0e0cb)

**Comment by Sonic-Amiga** [comment]
Probably i am missing the link. Perhaps because i am basing on an older version. Thank you for the response anyways.

**Comment by MassiPi** [comment]
i don't know if you want to add this, since i'm not using your hardware or your software, but Daikin FTXSxxG are working fine on S21 port, 3.3V compatible and first pin not connected.
Do not let set powerful or eco modes (Even if supported with remote controller), but power, mode, fan swing are working and temp inside, outside, coil and compressor idle state are reported
they also answer to a long list of commands but with no sense :)

**Comment by revk** [comment]
You should find the list on the Wiki is editable if you want to add with notes. And thank you.
