### ISSUE TITLE
Stylish CTX/FTX compatibility?

### ISSUE THREAD

**Issue by davea** [revk/ESP32-Faikin#73]
Does the module work with Daikin Stylish indoor units such as CTXA15/FTXA25 etc? I see the S21 wire harness listed as a compatible accessory on the Stylish brochure (ref EKRS21).

**Comment by revk** [comment]
If it has S21 lead, then probably. Someone else may be able to confirm. The wiki has a list of known compatible devices.

**Comment by shikousa** [comment]
Is there already anybody who is using the module for the CTXA/FTXA units? At the moment they are not listed as known working models in the Wiki.

**Comment by hargathor** [comment]
Interested since the last update from Daikin bricked two of my 3 devices which are CTXA15AW

**Comment by hargathor** [comment]
I can confirm that faikin is compatible with CTXA15AW
You just need a PAP-05V-S connector such as this one https://a.aliexpress.com/_Ev970JX

**Comment by savage7** [comment]
@hargathor Can you give me a tip how you opened the unit? I have only one screw at the front. 

![Groß (IMG_7570)](https://github.com/revk/ESP32-Faikin/assets/971353/6707d706-26b1-4280-8a60-3666f963e7bc)
![Groß (IMG_7569)](https://github.com/revk/ESP32-Faikin/assets/971353/19d0d408-3c51-47ca-a5e2-3ea9f9f9ddba)

**Comment by hargathor** [comment]
hello @savage7 

you need to remove the overall split as described in the manual. Remove the front cover using the blue thingy underneath (to open it manually you just need to pull gently, otherwise I thing there is a process using the remote control). Then you will be able to remove the main cover. There is three "pins" a the top and three at the bottom. Then you have two screws hidden by the cover where the air is blown. You will also need to unplug the connector on top of your picture.

Then you will be able to remove the cover of your split by gently pulling it. After that you will see a metal cover on the right side of the split. Remove the screws and you will have access to the motherboard and the S21 connector.

Don't forget to switch of the main power first

**Comment by savage7** [comment]
@hargathor Thanks taking the time two help me!
